<a href="https://colab.research.google.com/github/Iryna-Lytvynchuk/Data_Science/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1_homework

In [ ]:
#Task1
#v1
import numpy as np
a = np.matrix("0.05,0.07,0;0.05,0,0.06;1,1,1")
b = np.matrix("2250;1400;50000")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)
#v2
k = np.linalg.solve(a,b)
print(k)

[[10000.]
 [25000.]
 [15000.]]
[[10000.]
 [25000.]
 [15000.]]


In [ ]:
#v3
a = np.matrix("0.05,0.07,0;0.05,0,0.06;1,1,1")
b = np.matrix("2250;1400;50000")
a_det = np.linalg.det(a)
a_1 = np.matrix(a)
a_1[:,0] = b
a_2 = np.matrix(a)
a_2[:,1] = b
a_3 = np.matrix(a)
a_3[:,2] = b
x = [
     round((np.linalg.det(a_1))/a_det,),
     round((np.linalg.det(a_2))/a_det,),
     round((np.linalg.det(a_3))/a_det,),
]
print(x)

[10000, 25000, 15000]


In [ ]:
#Task2
a = np.matrix("1,-1,0;1,0,-1;1,1,1")
b = np.matrix("-120;100;1328")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)


[[436.]
 [556.]
 [336.]]


In [ ]:
#Task3
import itertools
a = np.matrix("3,0,3;6,0.25,0;1,0.333,1")
b = np.matrix("1;1;1")
a_inv = np.linalg.inv(a)
a_in_2, b_in_2, c_in_2 = 1/a_inv.dot(b)
print(f'a^2={a_in_2[0,0]}, b^2={b_in_2[0,0]}, c^2={c_in_2[0,0]}')

x = np.sqrt(a_inv.dot(b))
a_1 = [1/x[0,0]]
a_2 = [-1/x[0,0]]
a = a_1 + a_2
b_1 = [1/x[1,0]]
b_2 = [-1/x[1,0]]
b = b_1 + b_2
c_1 = [1/x[2,0]]
c_2 = [-1/x[2,0]]
c = c_1 + c_2
print(a)
print(b)
print(c)
k = list(itertools.product(a,b,c))
print(k)
       


a^2=12.012024048096194, b^2=0.49949999999999994, c^2=3.9986657771847893
[3.465836702456738, -3.465836702456738]
[0.7067531393633847, -0.7067531393633847]
[1.9996664164767055, -1.9996664164767055]
[(3.465836702456738, 0.7067531393633847, 1.9996664164767055), (3.465836702456738, 0.7067531393633847, -1.9996664164767055), (3.465836702456738, -0.7067531393633847, 1.9996664164767055), (3.465836702456738, -0.7067531393633847, -1.9996664164767055), (-3.465836702456738, 0.7067531393633847, 1.9996664164767055), (-3.465836702456738, 0.7067531393633847, -1.9996664164767055), (-3.465836702456738, -0.7067531393633847, 1.9996664164767055), (-3.465836702456738, -0.7067531393633847, -1.9996664164767055)]


In [ ]:
#Task4
a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[4.]
 [5.]
 [3.]]


In [ ]:
#Task5
def get_polynom(coords):
    a = ''
    b = ''
    for x,y in coords:
        a += str(x**2) + ',' + str(x) + ',1;'
        b += str(y)+';'
    print(a[:-1])
    print(b[:-1])
    a = np.matrix(a[:-1])
    b = np.matrix(b[:-1])
    print(f'a={a}')
    print(f'b={b}')
    return np.linalg.solve(a,b)
c = get_polynom(((1,12),(3,54),(-1,2)))
print(f'\n{c}')

1,1,1;9,3,1;1,-1,1
12;54;2
a=[[ 1  1  1]
 [ 9  3  1]
 [ 1 -1  1]]
b=[[12]
 [54]
 [ 2]]

[[4.]
 [5.]
 [3.]]


In [ ]:
#Task5
def get_polynom(coords):
    a = ''
    b = ''
    for x,y in coords:
        a += str(x**2) + ',' + str(x) + ',1;'
        b += str(y)+';'
    print(a[:-1])
    print(b[:-1])
    a = np.matrix(a[:-1])
    b = np.matrix(b[:-1])
    print(f'a={a}')
    print(f'b={b}')
    return np.linalg.lstsq(a, b, rcond=None)[0]
c = get_polynom(((1,12),(3,54),(-1,2)))
print(f'\n{c}')

1,1,1;9,3,1;1,-1,1
12;54;2
a=[[ 1  1  1]
 [ 9  3  1]
 [ 1 -1  1]]
b=[[12]
 [54]
 [ 2]]

[[4.]
 [5.]
 [3.]]


In [ ]:
#Task5
import numpy as np
import scipy.sparse
import scipy.sparse.linalg

def get_polynom(coords):
    a = ''
    b = ''
    for x,y in coords:
        a += str(x**2) + ',' + str(x) + ',1;'
        b += str(y)+';'
    a = scipy.sparse.csr_matrix(np.matrix(a[:-1]))
    b = scipy.sparse.csr_matrix(np.matrix(b[:-1]))
    return scipy.sparse.linalg.spsolve(a, b)

c = get_polynom(((1,12),(3,54),(-1,2)))
print(f'\n{c}')


[4. 5. 3.]
